name: evolphy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  fluentui_system_icons: ^1.1.238
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1C202A"
  image: "images/SplashLogo.png"
  
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: fonts/outfit/Outfit-Regular.ttf
        - asset: fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: fonts/outfit/Outfit-Bold.ttf
          weight: 700
